### PR TITLE
#425 Copy xmllint to bin

### PR DESCRIPTION
**Pull request by uilianries**
Related issue: https://github.com/bincrafters/community/issues/425

### CODE REVIEW

**Comment by Croydon** [comment]
I can't see in the logs that it actually copied xmllint

**Comment by Croydon** [comment]
On a side note I can't find the binary locally at all 🤔

**Review by Croydon — APPROVED** [review]
LGTM, thanks!

**Comment by uilianries** [comment]
Thanks for checking this!

**Comment by theirix** [comment]
Thanks, it's a good improvement!

**Pull request merged**
