### PR TITLE
testing -> stable

### PR DESCRIPTION
**Pull request by SSE4**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
the CI error seems unrelated to the changes

**Comment by uilianries** [comment]
I didn't find any difference when building x86 or x86_64 on mingw. Is it expected? Is there a specific flag, like -m32 ?

**Comment by ericLemanissier** [comment]
on appveyor, it uses a different compiler for x86 than x86_64 (eg https://ci.appveyor.com/project/bincrafters/conan-libxml2/builds/26084815/job/lxn3dl6cckhrq899?fullLog=true da79baa1f392d5cc5d0d05b5af3ef152fe9281e2 vs 424f435800f2c18b7ebdc5aaf0a0b870624bfdb6) so it does not need to pass -m32 flag to generate 32bits binaries. Do you mean that the recipe does not handle correctly the cross compilation situation when you build it locally, eg when using an x86_64 enabled mingw, and having settings.arch=x86 ?

**Comment by uilianries** [comment]
> on appveyor, it uses a different compiler for x86 than x86_64 (eg ci.appveyor.com/project/bincrafters/conan-libxml2/builds/26084815/job/lxn3dl6cckhrq899?fullLog=true da79baa1f392d5cc5d0d05b5af3ef152fe9281e2 vs 424f435800f2c18b7ebdc5aaf0a0b870624bfdb6) so it does not need to pass -m32 flag to generate 32bits binaries.

Understood.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
